name: Build and Deploy DocFX to Docs Branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build Documentation
        run: docfx docfx.json

      - name: Commit and Push to Docs Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout Docs || git checkout -b Docs
          rm -rf *
          cp -r _site/* .
          git add .
          git commit -m "Update documentation from main"
          git push origin Docs